import { Product, ProductCategory } from '@/src/core/domain/entities/Product';

export const MOCK_HONEY_PRODUCTS: Product[] = [
  {
    id: { value: '1' },
    slug: 'raw-organic-wildflower-honey',
    name: 'Raw Organic Wildflower Honey',
    description: 'Our premium raw organic wildflower honey is harvested from pristine meadows where bees collect nectar from diverse wildflowers. Never heated, never filtered - just pure, natural honey with all its beneficial enzymes and nutrients intact. This golden treasure offers a complex, floral flavor profile that changes subtly with each season. Perfect for drizzling over yogurt, adding to tea, or enjoying straight from the jar.',
    shortDescription: 'Pure, unfiltered wildflower honey from organic meadows',
    price: { amount: 24.99, currency: 'USD' },
    originalPrice: { amount: 32.99, currency: 'USD' },
    category: 'raw-honey',
    status: 'active',
    images: [
      {
        url: '/images/products/wildflower-honey-1.jpg',
        alt: 'Raw Organic Wildflower Honey Jar',
        isPrimary: true,
      },
      {
        url: '/images/products/wildflower-honey-2.jpg',
        alt: 'Wildflower Honey Pour',
        isPrimary: false,
      },
    ],
    tags: ['organic', 'raw', 'unfiltered', 'wildflower', 'natural'],
    rating: { average: 4.9, count: 328 },
    soldCount: 1542,
    features: [
      '100% Pure Raw Honey',
      'USDA Organic Certified',
      'Never Heated or Filtered',
      'Rich in Enzymes & Antioxidants',
      'Complex Floral Notes',
      'BPA-Free Glass Jar',
      'Sustainably Harvested',
    ],
    origin: 'Pacific Northwest, USA',
    weight: '500g',
    nutrition: {
      calories: 64,
      carbohydrates: '17g',
      sugars: '16g',
      protein: '0.1g',
      minerals: ['Calcium', 'Iron', 'Magnesium', 'Phosphorus', 'Potassium'],
    },
    specifications: {
      'Harvest Season': 'Summer 2024',
      'Moisture Content': '17.5%',
      'Color': 'Light Amber',
      'Consistency': 'Liquid',
      'Shelf Life': '2+ Years',
      'Storage': 'Room Temperature',
    },
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
  },
  
  {
    id: { value: '2' },
    slug: 'manuka-honey-umf-15',
    name: 'Manuka Honey UMF 15+',
    description: 'Authentic New Zealand Manuka honey with verified UMF 15+ rating. This rare and potent honey is produced by bees that pollinate the native Manuka bush. Known for its unique antibacterial properties and distinctive earthy, herbal flavor. Each batch is independently tested and certified by the UMF Honey Association. A luxurious superfood that supports immune health and digestive wellness.',
    shortDescription: 'Premium certified Manuka honey with powerful health benefits',
    price: { amount: 89.99, currency: 'USD' },
    category: 'raw-honey',
    status: 'active',
    images: [
      {
        url: '/images/products/manuka-honey-1.jpg',
        alt: 'Manuka Honey UMF 15+ Jar',
        isPrimary: true,
      },
    ],
    tags: ['manuka', 'umf', 'new-zealand', 'medicinal', 'premium'],
    rating: { average: 4.8, count: 892 },
    soldCount: 3201,
    features: [
      'UMF 15+ Certified',
      'MGO 514+ Rating',
      'Independently Lab Tested',
      'Monofloral Manuka',
      'Raw & Unpasteurized',
      'Antimicrobial Properties',
      'Traceability Guaranteed',
    ],
    origin: 'Waikato, New Zealand',
    weight: '250g',
    nutrition: {
      calories: 68,
      carbohydrates: '17g',
      sugars: '16g',
      protein: '0.2g',
      minerals: ['Methylglyoxal (MGO)', 'Hydrogen Peroxide'],
    },
    specifications: {
      'UMF Rating': '15+',
      'MGO Level': '514+ mg/kg',
      'Color': 'Dark Amber',
      'Texture': 'Thick & Creamy',
      'Certification': 'UMF HA Certified',
      'Harvest': 'Single Season',
    },
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-28'),
  },

  {
    id: { value: '3' },
    slug: 'lavender-infused-honey',
    name: 'Lavender Infused Honey',
    description: 'Artisan honey delicately infused with organic French lavender flowers. This elegant fusion creates a soothing, aromatic honey with calming floral notes. Perfect for sweetening evening tea, drizzling over desserts, or creating gourmet cheese pairings. The lavender essence promotes relaxation while the honey provides natural sweetness and beneficial properties.',
    shortDescription: 'Soothing honey infused with organic French lavender',
    price: { amount: 18.99, currency: 'USD' },
    originalPrice: { amount: 24.99, currency: 'USD' },
    category: 'flavored-honey',
    status: 'active',
    images: [
      {
        url: '/images/products/lavender-honey-1.jpg',
        alt: 'Lavender Infused Honey',
        isPrimary: true,
      },
    ],
    tags: ['lavender', 'infused', 'calming', 'artisan', 'floral'],
    rating: { average: 4.7, count: 156 },
    soldCount: 687,
    features: [
      'Real Lavender Flowers',
      'Organic Ingredients',
      'Handcrafted Small Batch',
      'Calming Properties',
      'Versatile Culinary Use',
      'Beautiful Purple Hue',
    ],
    origin: 'Provence, France',
    weight: '350g',
    specifications: {
      'Infusion Method': 'Cold Infusion',
      'Lavender Type': 'Lavandula Angustifolia',
      'Infusion Time': '30 Days',
      'Color': 'Light Purple',
      'Flavor Profile': 'Floral, Sweet, Herbal',
    },
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-12-03'),
  },

  {
    id: { value: '4' },
    slug: 'pure-honeycomb-raw',
    name: 'Pure Raw Honeycomb',
    description: 'Experience honey in its most natural form with our pure raw honeycomb. Each piece is carefully cut from pristine hives, complete with beeswax comb filled with raw, unprocessed honey. Chew the wax for a unique textural experience while enjoying the purest honey possible. The edible beeswax provides additional health benefits and can be used in various applications.',
    shortDescription: 'Honey in its most natural form - straight from the hive',
    price: { amount: 34.99, currency: 'USD' },
    category: 'honeycomb',
    status: 'active',
    images: [
      {
        url: '/images/products/honeycomb-1.jpg',
        alt: 'Pure Raw Honeycomb',
        isPrimary: true,
      },
    ],
    tags: ['honeycomb', 'raw', 'beeswax', 'natural', 'premium'],
    rating: { average: 4.9, count: 213 },
    soldCount: 891,
    features: [
      'Straight from the Hive',
      '100% Edible Including Wax',
      'Maximum Enzyme Content',
      'Unique Texture & Experience',
      'No Processing',
      'Natural Preservative Properties',
      'Artisanal Presentation',
    ],
    origin: 'Montana, USA',
    weight: '400g',
    specifications: {
      'Comb Type': 'Worker Bee Comb',
      'Wax Quality': 'Food Grade',
      'Cell Size': 'Standard',
      'Purity': '100% Natural',
      'Harvest Method': 'Sustainable',
    },
    createdAt: new Date('2024-07-22'),
    updatedAt: new Date('2024-12-05'),
  },

  {
    id: { value: '5' },
    slug: 'bee-pollen-granules',
    name: 'Premium Bee Pollen Granules',
    description: 'Superfood bee pollen collected by foraging bees from diverse flowering plants. These golden granules are packed with proteins, vitamins, minerals, and antioxidants. Often called "nature\'s perfect food," bee pollen supports immune function, increases energy, and promotes overall wellness. Sprinkle over smoothie bowls, yogurt, or enjoy by the spoonful.',
    shortDescription: 'Nutrient-dense superfood packed with vitamins and minerals',
    price: { amount: 29.99, currency: 'USD' },
    category: 'bee-products',
    status: 'active',
    images: [
      {
        url: '/images/products/bee-pollen-1.jpg',
        alt: 'Bee Pollen Granules',
        isPrimary: true,
      },
    ],
    tags: ['bee-pollen', 'superfood', 'protein', 'energy', 'wellness'],
    rating: { average: 4.6, count: 445 },
    soldCount: 2103,
    features: [
      '100% Pure Bee Pollen',
      'Rich in Protein (40%)',
      'Contains 22 Amino Acids',
      'Natural Energy Booster',
      'Supports Immune System',
      'Easy to Use',
      'Resealable Pouch',
    ],
    origin: 'Spain',
    weight: '250g',
    nutrition: {
      calories: 90,
      carbohydrates: '13g',
      protein: '5g',
      minerals: ['B-Vitamins', 'Vitamin C', 'Calcium', 'Magnesium', 'Iron'],
    },
    specifications: {
      'Pollen Source': 'Multifloral',
      'Protein Content': '40%',
      'Moisture': '6-8%',
      'Serving Size': '1 Teaspoon (5g)',
      'Daily Dose': '1-2 Teaspoons',
    },
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date('2024-11-30'),
  },

  {
    id: { value: '6' },
    slug: 'royal-jelly-capsules',
    name: 'Royal Jelly Supplement Capsules',
    description: 'Premium freeze-dried royal jelly in convenient capsule form. Royal jelly is the exclusive food of the queen bee, packed with vitamins, minerals, and unique fatty acids. Supports skin health, hormonal balance, and cognitive function. Our capsules preserve the potency of fresh royal jelly while offering easy daily supplementation.',
    shortDescription: 'Queen bee superfood for vitality and longevity',
    price: { amount: 44.99, currency: 'USD' },
    originalPrice: { amount: 54.99, currency: 'USD' },
    category: 'supplements',
    status: 'active',
    images: [
      {
        url: '/images/products/royal-jelly-1.jpg',
        alt: 'Royal Jelly Capsules',
        isPrimary: true,
      },
    ],
    tags: ['royal-jelly', 'supplement', 'anti-aging', 'hormonal-health', 'capsules'],
    rating: { average: 4.7, count: 567 },
    soldCount: 1876,
    features: [
      'Freeze-Dried for Potency',
      '1000mg per Capsule',
      '60 Capsules (2 Month Supply)',
      'Rich in 10-HDA',
      'Supports Skin & Hair',
      'Hormonal Balance',
      'Third-Party Tested',
    ],
    origin: 'China (Quality Controlled)',
    weight: '60 capsules',
    nutrition: {
      minerals: ['B-Complex Vitamins', 'Pantothenic Acid', 'Biotin', 'Amino Acids'],
    },
    specifications: {
      'Capsule Type': 'Vegetarian',
      'Royal Jelly Content': '1000mg',
      '10-HDA Content': '6%',
      'Serving Size': '1 Capsule',
      'Servings Per Container': '60',
      'Storage': 'Cool, Dry Place',
    },
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-12-02'),
  },

  {
    id: { value: '7' },
    slug: 'honey-face-mask-skincare',
    name: 'Raw Honey Hydrating Face Mask',
    description: 'Luxurious face mask featuring raw honey as the star ingredient, combined with organic botanicals and essential oils. Honey\'s natural antibacterial and humectant properties deeply hydrate, soothe inflammation, and promote a radiant complexion. Suitable for all skin types, especially dry and sensitive skin. Paraben-free, sulfate-free, and cruelty-free.',
    shortDescription: 'Nourishing face mask with raw honey and botanicals',
    price: { amount: 36.99, currency: 'USD' },
    category: 'skincare',
    status: 'active',
    images: [
      {
        url: '/images/products/honey-mask-1.jpg',
        alt: 'Honey Face Mask',
        isPrimary: true,
      },
    ],
    tags: ['skincare', 'face-mask', 'hydrating', 'natural', 'organic'],
    rating: { average: 4.8, count: 289 },
    soldCount: 1123,
    features: [
      'Raw Honey Base',
      'Organic Ingredients',
      'Deep Hydration',
      'Anti-Inflammatory',
      'Suitable for Sensitive Skin',
      'Cruelty-Free & Vegan',
      'Recyclable Packaging',
    ],
    origin: 'California, USA',
    weight: '100ml',
    specifications: {
      'Skin Types': 'All Types',
      'Usage': '2-3 Times Weekly',
      'Application Time': '15-20 Minutes',
      'Key Ingredients': 'Raw Honey, Aloe Vera, Chamomile',
      'Texture': 'Creamy',
      'Scent': 'Light Floral',
    },
    createdAt: new Date('2024-08-05'),
    updatedAt: new Date('2024-12-04'),
  },

  {
    id: { value: '8' },
    slug: 'cinnamon-honey-blend',
    name: 'Cinnamon Honey Wellness Blend',
    description: 'Powerful combination of raw honey and Ceylon cinnamon, two ancient superfoods renowned for their health benefits. This warming blend supports metabolism, blood sugar balance, and digestive health. The sweet and spicy flavor makes it perfect for morning rituals - stir into warm water, spread on toast, or add to oatmeal.',
    shortDescription: 'Ancient wellness blend of honey and Ceylon cinnamon',
    price: { amount: 22.99, currency: 'USD' },
    category: 'flavored-honey',
    status: 'active',
    images: [
      {
        url: '/images/products/cinnamon-honey-1.jpg',
        alt: 'Cinnamon Honey Blend',
        isPrimary: true,
      },
    ],
    tags: ['cinnamon', 'wellness', 'metabolism', 'digestive-health', 'spiced'],
    rating: { average: 4.7, count: 398 },
    soldCount: 1654,
    features: [
      'Ceylon Cinnamon (True Cinnamon)',
      'Raw Unfiltered Honey',
      'Metabolism Support',
      'Blood Sugar Balance',
      'Anti-Inflammatory',
      'Daily Wellness Ritual',
      'Naturally Sweet & Spicy',
    ],
    origin: 'Sri Lanka & USA',
    weight: '400g',
    specifications: {
      'Cinnamon Type': 'Ceylon (Cinnamomum Verum)',
      'Cinnamon Content': '15%',
      'Flavor Profile': 'Sweet, Warm, Spicy',
      'Best Used': 'Morning Routine',
      'Mixing Method': 'Cold Blended',
    },
    createdAt: new Date('2024-09-12'),
    updatedAt: new Date('2024-12-06'),
  },

  {
    id: { value: '9' },
    slug: 'propolis-tincture',
    name: 'Propolis Extract Tincture',
    description: 'Concentrated propolis tincture made from high-quality bee propolis. Known as "bee glue," propolis is a resinous mixture bees create from tree sap, used to protect the hive. Rich in antioxidants and flavonoids, propolis supports immune function, throat health, and oral hygiene. A few drops go a long way in supporting your wellness routine.',
    shortDescription: 'Immune-supporting bee propolis in liquid form',
    price: { amount: 26.99, currency: 'USD' },
    category: 'bee-products',
    status: 'active',
    images: [
      {
        url: '/images/products/propolis-1.jpg',
        alt: 'Propolis Tincture',
        isPrimary: true,
      },
    ],
    tags: ['propolis', 'immune-support', 'tincture', 'antioxidants', 'throat-health'],
    rating: { average: 4.6, count: 234 },
    soldCount: 892,
    features: [
      'High-Potency Extract',
      'Alcohol-Based Tincture',
      'Rich in Flavonoids',
      'Immune System Support',
      'Throat & Oral Health',
      'Easy Dropper Application',
      '2 Month Supply',
    ],
    origin: 'Brazil',
    weight: '30ml',
    specifications: {
      'Propolis Content': '30%',
      'Base': 'Organic Alcohol',
      'Serving Size': '10-15 Drops',
      'Servings Per Bottle': '60',
      'Usage': 'Daily or as Needed',
      'Storage': 'Cool, Dark Place',
    },
    createdAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-11-29'),
  },

  {
    id: { value: '10' },
    slug: 'acacia-honey-light',
    name: 'Pure Acacia Honey - Light & Delicate',
    description: 'Exquisite acacia honey known for its remarkably light color, mild flavor, and high fructose content that keeps it liquid longer. Sourced from acacia tree blossoms, this honey has a clean, delicate sweetness that doesn\'t overpower other flavors. Ideal for sweetening beverages, baking, or as a natural sweetener for those who prefer a subtle honey taste.',
    shortDescription: 'Delicate, light honey that stays liquid naturally',
    price: { amount: 19.99, currency: 'USD' },
    category: 'raw-honey',
    status: 'active',
    images: [
      {
        url: '/images/products/acacia-honey-1.jpg',
        alt: 'Acacia Honey',
        isPrimary: true,
      },
    ],
    tags: ['acacia', 'light-honey', 'mild', 'liquid', 'baking'],
    rating: { average: 4.8, count: 412 },
    soldCount: 1789,
    features: [
      'Light & Mild Flavor',
      'Stays Liquid Naturally',
      'Low Glycemic Index',
      'Perfect for Baking',
      'Doesn\'t Crystallize',
      'Pure Monofloral Honey',
      'Elegant Taste',
    ],
    origin: 'Hungary',
    weight: '500g',
    nutrition: {
      calories: 64,
      carbohydrates: '17g',
      sugars: '17g',
      protein: '0g',
      minerals: ['Trace Minerals'],
    },
    specifications: {
      'Color': 'Extra Light Amber',
      'Flavor': 'Mild, Clean, Delicate',
      'Consistency': 'Liquid',
      'Fructose/Glucose Ratio': 'High Fructose',
      'Crystallization': 'Very Slow',
      'Acacia Type': 'Robinia Pseudoacacia',
    },
    createdAt: new Date('2024-05-30'),
    updatedAt: new Date('2024-12-07'),
  },
];

/**
 * 🎯 HELPER: Exportar por categoría para facilitar testing
 */
export const PRODUCTS_BY_CATEGORY: Record<ProductCategory, Product[]> = {
  'raw-honey': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'raw-honey'),
  'flavored-honey': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'flavored-honey'),
  'honeycomb': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'honeycomb'),
  'bee-products': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'bee-products'),
  'skincare': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'skincare'),
  'supplements': MOCK_HONEY_PRODUCTS.filter(p => p.category === 'supplements'),
};